config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'home/index'
  root to: 'readers/home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/blog/:id' => 'readers/posts#show', as: :blog_post
  
  scope module: 'users' do
    resources :posts do
      resources :comments
      resources :elements
    end
  end
  
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post
  
end

app/models/element.rb
class Element < ApplicationRecord
  belongs_to :post

  validates :element_type, inclusion: { in: ['paragraph', 'image', 'video-embed'] }

  has_rich_text :content
  has_one_attached :image
  
  def paragraph?
    element_type == 'paragraph'
  end

  def image?
    element_type == 'image'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]
  
  belongs_to :user
  has_many :elements, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_one_attached :header_image

  scope :published, -> do
    where(published: true)
  end

  scope :most_recently_published, -> do
    order(published_at: :desc)
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy 
  has_many :comments, dependent: :nullify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    

    def current_or_guest_user
        if current_user
          if session[:guest_user_id] && session[:guest_user_id] != current_user.id
            logging_in
            # reload guest_user to prevent caching problems before destruction
            guest_user(with_retry = false).try(:reload).try(:destroy)
            session[:guest_user_id] = nil
          end
          current_user
        else
          guest_user
        end
      end
    
      # find guest_user object associated with the current session,
      # creating one as needed
      def guest_user(with_retry = true)
        # Cache the value the first time it's gotten.
        @cached_guest_user ||= User.find(session[:guest_user_id] ||= create_guest_user.id)
    
      rescue ActiveRecord::RecordNotFound # if session[:guest_user_id] invalid
         session[:guest_user_id] = nil
         guest_user if with_retry
      end
    
      private
    
      # called (once) when the user logs in, insert any code your application needs
      # to hand off from guest_user to current_user.
      def logging_in
        # For example:
        # guest_comments = guest_user.comments.all
        # guest_comments.each do |comment|
          # comment.user_id = current_user.id
          # comment.save!
        # end
      end
      
      def transfer_guest_to_user
        # At this point you have access to:
        #   * current_user - the user they've just logged in as
        #   * guest_user - the guest user they were previously identified by
        # 
        # After this block runs, the guest_user will be destroyed!
      end

      def create_guest_user
        u = User.new(email: "Anonymous_#{Time.now.to_i}#{rand(100)}@example.com")
        u.save!(validate: false)
        session[:guest_user_id] = u.id
        u
      end
end

app/controllers/concerns/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/concerns/readers_controller.rb
class ReadersController < ApplicationController
    skip_before_action :authenticate_user!
    
    layout 'readers'
end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController

    layout 'users'
end

app/controllers/readers/home_controller.rb
module Readers
    class HomeController < ReadersController
      def index
        @posts = Post.published.most_recently_published.paginate(page: params[:page], per_page: 3)
      end
    end
end

app/controllers/readers/posts_controller.rb
module Readers
    class PostsController < ReadersController
      
      def show
        @post = Post.published.friendly.find(params[:id])
      end
  
    end
end

app/controllers/users/comments_controller.rb
module Users
    class CommentsController < UsersController
        skip_before_action :authenticate_user!
        
        def create
            @post = Post.find(params[:post_id])
            @comment = current_or_guest_user.comments.new(comment_params)
            @comment.post = @post

            if !@comment.save
                flash[:notice] = @comment.errors.full_messages.to_sentence
            end
            redirect_to blog_post_path(params[:post_id])
            
        end

        

        private
       
        def comment_params
            params.require(:comment).permit(:content, :parent_id)
        end
        
    end
end

app/controllers/users/elements_controller.rb
module Users
  class ElementsController < UsersController
    before_action :set_post
    before_action :set_element, only: [:update, :destroy]
  
    # POST /elements
    def create
      @element = @post.elements.build(element_params)
  
      if @element.save
        notice = nil
      else
        notice = @element.errors.full_messages.join(". ") << "."
      end
      redirect_to edit_post_path(@post), notice: notice
    end
  
    # PATCH/PUT /elements/1
    def update
      @element.update(element_params)
    end
  
    # DELETE /elements/1
    def destroy
      @element.destroy
      redirect_to edit_post_path(@element.post)
    end
  
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_user.posts.find(params[:post_id])
    end

    def set_element
      @element = @post.elements.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def element_params
      params.require(:element).permit(:element_type, :content, :image)
    end
  end  
end

app/controllers/users/posts_controller.rb
module Users
  class PostsController < UsersController
    before_action :set_post, only: [:edit, :update, :destroy]
  
    # GET /posts
    def index
      @posts = current_user.posts
    end
  
    def show
      @post = Post.find(params[:id])
    end
  
    # GET /posts/new
    def new
      @post = current_user.posts.build
    end
  
    # GET /posts/1/edit
    def edit
      @element = @post.elements.build
    end
  
    # POST /posts
    def create
      @post = current_user.posts.build(post_params)

      if @post.save
        redirect_to edit_post_path(@post)
      else
        broadcast_errors @post, post_params
      end
    end
  
    # PATCH/PUT /posts/1
    def update
      if @post.update(post_params)
        redirect_to edit_post_path(@post)
      else
        broadcast_errors @post, post_params
      end
    end
  
    # DELETE /posts/1 
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_user.posts.friendly.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def post_params
        params.require(:post).permit(:title, :description, :header_image )
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MainoEstagBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body class='bg-light'>
    <div class="container">
      <%= render 'shared/navbar' %>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
      <%= render 'shared/footer' %>
    </div>  
  </body>

</html>

app/views/layouts/readers.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MainoEstagBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body class='bg-light readers'>
    
    <div class="container">
      <%= render 'shared/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
    
  </body>
  
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MainoEstagBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body class='bg-light users'>
    
    <div class="container"> 
      <%= render 'shared/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>

  </body>
  
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/readers/comments/_comment.html.erb
<article>
    <p><%= comment.content %></p>
    <small> by <%= comment.user != nil ? comment.user.email.split("@")[0].split("_")[0] : 'Anonymous' %></small>
</article>
<hr />

app/views/readers/index.html.erb
<div class="mt-5">
  <div class="row">
  <% @posts.each do |post| %>
    <div class="col-md-6 col-lg-4">
      <div class="card reader-post-card">
        <% if post.header_image.present? %>
          <div class="reader-header-image" style="background-image: url(<%= url_for(post.header_image) %>);"></div>
        <% else %>
          <div class="reader-header-image" style="background-image: url(<%= asset_path 'default-placeholder.png' %>);"></div>
        <% end %>
        <div class="card-body d-flex flex-column">
          <h5 class="card-title"><%= post.title %></h5>
          <p class="card-text"><%= truncate(post.description, length: 250) %></p>
          <%= link_to "Read Post", blog_post_path(post), class: 'btn btn-primary mt-auto' %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
  <nav class="mt-5">
    <%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, list_classes: %w(pagination justify-content-center)  %>
  </nav>
</div>

app/views/readers/posts/_form.html.erb
<form action="<%= post_comments_path(@post) %>" method="post" class="mb-3">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <div>
        <textarea name="comment[content]" rows="5" cols="50"></textarea>
    </div>
    <input type="submit" value="Post Comment" class="btn btn-primary mt-1">
</form>

app/views/readers/posts/show.html.erb
<div class="row">
  <div class="col-lg-10 offset-lg-1">
    <div class="card post-card mb-5">
      <div class="show-header-image" style="background-image: url(<%= url_for(@post.header_image) %>)"></div>
      <div class="card-body">
        <div class="pl-5 pr-5 pt-4 pb-4">
          <h1 class="card-title mb-5"><%= @post.title %></h1>
          <% @post.elements.each do |element| %>
            <% if element.image.present? %>
              <div class="show-image-element mb-5">
                <%= cl_image_tag element.image.key %>
              </div>
            <% else %>
              <div class="content-element mb-5">
                <%= element.content %>
              </div>
            <% end %>
            
          <% end %>

        </div>
        
      </div>

    </div>
    <div class="d-flex justify-content-center container mt-5 mb-5">
      <div class="row card-header">
        <div class="col-sm-5 col-md-6 col-12 pb-4">
          
          <%= render 'form', locals: { post: @post, parent: nil }, class: "mb-5" %>
          <%= render @post.comments.order(id: :desc) %>
          
        </div>
      </div>
    </div> 
  </div>
</div>

app/views/shared/_footer.html.erb

    <div class="footer mt-5">
      <h3>Blog</h3>
      <div class="footer-links">
        <a class="social-icon" href="https://github.com/vkaraujo" target="_blank"><i class="fab fa-github"></i></a>
        <a class="social-icon" href="https://api.whatsapp.com/send?phone=5521993244202&text=Olá, Viktor" target="_blank"><i class="fab fa-whatsapp"></i></a>
        <a class="social-icon" href="https://www.linkedin.com/in/viktor-waissmann-de-araujo-62928640/" target="_blank"><i class="fab fa-linkedin-in"></i></a>
      </div>
    </div>


app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon d-flex justify-content-around">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Posts", posts_path, class: "nav-link" %>
        </li>
        
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <%= link_to edit_user_registration_path do %>
          <i class="fas fa-user-circle fa-2x ml-3"></i>
        <% end %>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/elements/update.js.erb
var element = document.getElementById('element-<%= @element.id %>-form')

element.classList.add('d-none')
element.previousElementSibling.classList.remove('d-none')

var html = "<div class='trix-content'><%= @element.content.body.html_safe %></div>"

element.previousElementSibling.innerHTML = html

app/views/users/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :header_image, as: :file %>
    <div class="mt-1">
      <% if post.header_image.present? %>
        <small>Current image:</small>
        <%= cl_image_tag @post.header_image.key, width: '100%' %>
      <% end%>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/users/posts/_postBody.html.erb
<div class="card mb-5">
    <div class="card-header text-right">
        <% if @post.published? %>
            <b>Published</b>
            <%= time_ago_in_words(@post.published_at) %> ago
        <% else %>
            Unpublished
        <% end %>
    </div>
    
    <div class="card-body pt-5" data-controller="elements">
        <% if @post.elements.none? { |element| element.persisted? } %>
            <div class="p-4 text-center">
                <h2 class='text-secondary'>
                <i class="fas fa-lightbulb"></i>
                </h2>
                <p>Click the icons above to add elements to this post.</p>
            </div>
        <% else %>
            <ul id="elements" data-action="drop->elements#sort">
                <% @post.elements.order(position: :asc).each do |element| %>
                    <% if element.persisted? %>
                        <li data-id="<%= element.id %>" class='element-item'>
                    
                            <% if element.paragraph? %>
                                <div class="mb-4 p-3 paragraph">
                                    <div class="paragraph-content">
                                        <% if element.content.present? %>
                                            <%= element.content %>
                                        <% else %>
                                            Click to add content.
                                        <% end %>
                                    </div>

                                    <div class="paragraph-form d-none" id='element-<%= element.id %>-form'>
                                        <%= form_with(model: [@post, element]) do |form| %>
                                            <%= form.rich_text_area :content %>
                                            <div class="mt-3 d-flex justify-content-between">
                                                <div>
                                                    <%= form.submit "Save", class: 'btn btn-primary' %>
                                                    <a href="#" class='cancel btn btn-secondary'>Cancel</a>
                                                </div>
                                                <%= link_to 'Delete', post_element_path(@post, element), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?" } %>
                                            </div>
                                        <% end %>
                                    </div>

                                </div>

                            <% elsif element.image? %>

                                <div class="mb-4 p-3 image">
                                    <% if element.image.present? %>
                                        <%= link_to post_element_path(@post, element), method: :delete, class: 'delete-btn btn btn-danger mt-2 float-right', data: { confirm: "Are you sure?" } do %>
                                            <i class='fas fa-times'></i>
                                        <% end %>
                                        <%= cl_image_tag element.image.key %>
                                    <% else %>
                                        <%= form_with(model: [@post, element]) do |form| %>
                                            <%= form.file_field :image %>
                                            <div class="mt-3">
                                                <%= form.submit "Save", class: 'btn btn-primary' %>
                                                <a href="#" class='cancel btn btn-secondary'>Cancel</a>
                                            </div>
                                        <% end %>
                                    <% end %>
                                </div>

                            <% end %>
                        </li>
                    <% end %> 
                <% end %>
            </ul>
        <% end %>
    </div>
</div>

app/views/users/posts/_postHead.html.erb
<%= link_to 'Back', posts_path, class: 'btn btn-dark mb-3' %>
<div class="card">
    <div class="card-header">
        <h6 class="card-title mb-0">Editing Post</h6>
    </div>
    <div class="card-body">
        <%= render 'form', post: @post %>
    </div>
    <div class="card-footer">
        <% if @post.published? %>
            <a href="#"
            class='btn btn-secondary btn-block'
            data-reflex='click->PublisherReflex#unpublish'
            data-post-id='<%= @post.id %>'>
            Unpublish
            </a>
        <% else %>
            <a href="#"
            class='btn btn-dark btn-block'
            data-reflex='click->PublisherReflex#publish'
            data-post-id='<%= @post.id %>'>
            Publish
            </a>
        <% end %>
    </div>
    <div class="card-footer">
        <%= link_to 'Delete', post_path, method: :delete, class: 'btn btn-danger btn-block', data: { confirm: "Are you sure?" } %>
    </div>
</div>

app/views/users/posts/edit.html.erb
<div class="row">
    <div class="col-md-4">
        <%= render 'postHead', post: @post %>
    </div>
    <div class="col-md-8">
        <div class="mb-3">
            <%= form_with(model: [@post, @element], html: { class: 'float-left mr-1' }) do |form| %>
                <%= form.hidden_field :element_type, value: 'paragraph' %>
                <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
                    <i class="fas fa-paragraph"></i>
                <% end %>
            <% end %>
            <%= form_with(model: [@post, @element]) do |form| %>
                <%= form.hidden_field :element_type, value: 'image' %>
                <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
                    <i class="fas fa-image"></i>
                <% end %>
            <% end %>
        </div>
        <%= render 'postBody', post: @post %>
    </div>
</div>

app/views/users/posts/index.html.erb
<h4 class='d-flex justify-content-between mb-4'>
  <span >My Posts</span>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
</h4>

<% @posts.each do |post| %>
  <%= link_to edit_post_path(post), class: 'text-decoration-none' do %>
    <div class="card mb-3 post-card">
      <div class="card-body">
        <div class="row">
          <div class="col-md-2">
            <% if post.header_image.present? %>
              <div class="header-img" style="background-image: url(<%= url_for(post.header_image) %>);"></div>
            <% else %>
              <div class="reader-header-image" style="background-image: url(<%= asset_path 'default-placeholder.png' %>);"></div>
            <% end %>
          </div>
          <div class="col-md-10">
            <% if post.published? %>
              <span class='badge badge-primary mb-3'>Published</span>
            <% else %>
              <span class='badge badge-secondary mb-3'>Unpublished</span>
            <% end %>
            <h5 class='card-title mb-2 text-dark'><%= post.title %></h5>
            <p class='text-secondary mb-0'><%= post.description %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/users/posts/new.html.erb
<div class="row">
  <div class="col-md-4">

    <%= link_to 'Back', posts_path, class: 'btn btn-dark mb-3' %>

    <div class="card">
      <div class="card-header">
        <h6 class='card-title mb-0'>New Post</h6>
      </div>
      <div class="card-body">
        <%= render 'form', post: @post %>
      </div>
    </div>
  </div>
</div>